---

- hosts: localhost

  collections:
  - kubernetes.core

  tasks:

  - name: dependancy
    shell: "velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.6.0 --bucket kube-backup-nagesh --backup-location-config region=us-east-1 --snapshot-location-config region=us-east-1 --secret-file /tmp/credentials-velero"


  # - name: Get a list of all pods from any namespace
  #   kubernetes.core.k8s_info:
  #     kind: Pod
  #     namespace: velero
  #   register: pod_list


  # - name: create k8s pod
  #   kubernetes.core.k8s:
  #     src: deployment.yaml
  #     namespace: dev-game-app
  #     state: present


  # - name: create services
  #   kubernetes.core.k8s:
  #     src: service.yaml
  #     namespace: dev-game-app
  #     state: present

     
  # - name: create route
  #   kubernetes.core.k8s:
  #     src: route.yaml
  #     namespace: dev-game-app
  #     state: present